server:
  port: 8084

spring:
  application:
    name: customer-service

  profiles:
    active: local

  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: customerdb
    redis:
      host: localhost
  cache:
    redis:
      time-to-live: 60000

springdoc:
  swagger-ui:
    path: /api/docs

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/