server:
  port: 8080

spring:
  application:
    name: customer-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  data:
    mongodb:
      uri: ${MONGO_URI:mongodb://mongo:27017}
      database: customerdb

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    redis:
      time-to-live: 60000

# swagger
springdoc:
  swagger-ui:
    path: /api/docs

# prometheus
management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus"]
    endpoint:
      metrics:
        enabled: true
      health:
        show-details: always
      prometheus:
        enabled: true
