server:
  port: 8083

spring:
  application:
    name: payment-service

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/paymentdb?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
  cache:
    redis:
      time-to-live: 60000

springdoc:
  swagger-ui:
    path: /api/docs