server:
  port: 8080

spring:
  application:
    name: order-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    redis:
      time-to-live: 60000

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    template:
      default-topic: ${KAFKA_TOPIC}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: order-event:com.serhat.orderservice.model.event.OrderPlacedEvent

# swagger
springdoc:
  swagger-ui:
    path: /api/docs

# prometheus
management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus"]
    endpoint:
      metrics:
        enabled: true
      health:
        show-details: always
      prometheus:
        enabled: true
