server:
  port: 8082

spring:
  application:
    name: order-service

  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    url: jdbc:mysql://localhost:3306/orderdb?createDatabaseIfNotExist=true&useSSL=false&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: "root"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: localhost
  cache:
    redis:
      time-to-live: 60000

  kafka:
    bootstrap-servers: localhost:9092
    template:
      default-topic: order-events
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: order-event:com.serhat.orderservice.model.event.OrderPlacedEvent

springdoc:
  swagger-ui:
    path: /api/docs