server:
  port: 8761

spring:
  application:
    name: product-service

  profiles:
    active: local

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
