server:
  port: 8080

spring:
  application:
    name: product-service

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/productdb}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
  cache:
    redis:
      time-to-live: 60000

  kafka:
    template:
      default-topic: ${KAFKA_TOPIC:order-events}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      group-id: ${GROUP_ID:product-group}
      properties:
        spring:
          json:
            type:
              mapping: order-event:com.serhat.productservice.model.event.OrderPlacedEvent

springdoc:
  swagger-ui:
    path: /api/docs

# prometheus
management:
  endpoints:
    web:
      exposure:
        include: ["health", "metrics", "prometheus"]
    endpoint:
      metrics:
        enabled: true
      health:
        show-details: always
      prometheus:
        enabled: true
