server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://customer-service:8080
          predicates:
            - Path=/api/v1/customers
        - id: order-service
          uri: http://order-service:8080
          predicates:
            - Path=/api/v1/orders
        - id: product-service
          uri: http://product-service:8080
          predicates:
            - Path=/api/v1/products
        - id: payment-service
          uri: http://payment-service:8080
          predicates:
            - Path=/api/v1/payments