server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: customer-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/v1/customers
        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/orders
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/products
        - id: payment-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/payments