name: CI/CD - Customer Service
 
on:
  push:
    branches:
    - master
    paths:
    - 'customer-service/**'

env:
  service-name: customer-service

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Build Project with Maven
        run: cd ${{ env.service-name }} && mvn clean package -DskipTests && cd ..
      
      - name: Build and Tag Docker Image
        run: docker build -f ./${{ env.service-name }}/Dockerfile -t ${{ env.service-name }} . && docker tag ${{ env.service-name }} ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.service-name }}:latest

      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.service-name }}:latest
